---
exclude: '^(venv|\.vscode)' # regex
repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.4.1"
    hooks:
      - id: prettier
        args: ["--print-width=135"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black